S01 us10 movie detail
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #12
Opened 2022-10-07 11:44 UTC by epereira

The first overview for the movie detail page (in progress)

2022-10-07 12:49 UTC, SkeidoK approved these changes, later dismissed

2022-10-07 14:54 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-07 14:55 UTC, SkeidoK submitted a review, later dismissed

2022-10-10 07:11 UTC, YDrogen requested changes

2022-10-10 07:11 UTC, YDrogen commented on src/components/Rating.jsx
> +  note || (note = 0);
Que fait ce code ?

2022-10-10 07:11 UTC, YDrogen commented on src/components/Rating.jsx
> +    starRender.push(i <= rating ? `${star_color_yes}` : `${star_color_no}`);
Soit c'est une `const` qui ne bouge pas, soit un state qui peut évoluer

2022-10-10 07:11 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +  let mounted = true;
Certainement pas
Soit une `const`, soit un state

2022-10-10 07:11 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +      mounted = false;
Le `mounted` est déjà géré automatiquement par React

2022-10-10 07:24 UTC, epereira commented on src/pages/detail/Movie.jsx
> +  let mounted = true;
juste un boolean dont la valeur doit changer

2022-10-10 07:26 UTC, epereira commented on src/pages/detail/Movie.jsx
> +      mounted = false;
Boolean pour ne pas lancer deux fois la requête du useEffect

2022-10-10 09:40 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-10 09:40 UTC, epereira commented on src/components/Rating.jsx
> +  note || (note = 0);
Modifié et fichier supprimé

2022-10-10 09:41 UTC, epereira commented on src/components/Rating.jsx
> +    starRender.push(i <= rating ? `${star_color_yes}` : `${star_color_no}`);
component deleted

2022-10-10 09:51 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-10 10:02 UTC, DangirasH submitted a review, later dismissed

2022-10-10 10:31 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-10 12:00 UTC, paul-chatelain-fernandes approved these changes

2022-10-10 12:16 UTC, SkeidoK approved these changes

2022-10-10 12:32 UTC, YDrogen approved these changes
Top 👌

2022-10-10 12:35 UTC, merged