S01 us10 movie add actors
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #17
Opened 2022-10-12 16:26 UTC by epereira

2022-10-13 08:01 UTC, paul-chatelain-fernandes approved these changes

2022-10-13 12:19 UTC, SkeidoK approved these changes, later dismissed

2022-10-13 14:08 UTC, YDrogen requested changes

2022-10-13 14:08 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    const [...actors] = response["cast"];
# ???
<img src="https://media.tenor.com/j2X1CcR6TP8AAAAd/closeup-pardon.gif" width="400" height="400" />

2022-10-13 14:08 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    actors && setCharacters(actors);
# ???
![Alt](https://media.tenor.com/j2X1CcR6TP8AAAAd/closeup-pardon.gif)

2022-10-13 14:08 UTC, YDrogen commented on src/pages/detail/movie.scss
> +img.pic-star {
Pourquoi utiliser du CSS dans un `.scss` ?

2022-10-13 15:24 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-13 19:34 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    const [...actors] = response["cast"];
fixed

2022-10-13 19:35 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    actors && setCharacters(actors);
fixed

2022-10-13 19:35 UTC, epereira commented on src/pages/detail/movie.scss
> +img.pic-star {
fixed

2022-10-14 07:18 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-14 07:18 UTC, DangirasH submitted a review, later dismissed

2022-10-14 07:25 UTC, YDrogen requested changes

2022-10-14 07:25 UTC, YDrogen commented on src/pages/detail/movie.scss
> +  &:hover {
au mauvais endroit

2022-10-14 07:30 UTC, epereira commented on src/pages/detail/movie.scss
> +  &:hover {
fixed

2022-10-14 07:33 UTC, SkeidoK approved these changes

2022-10-14 07:35 UTC, DangirasH approved these changes

2022-10-14 07:45 UTC, YDrogen approved these changes

2022-10-14 07:50 UTC, merged