Trending Cards Home Finished Axios and Design
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #19
Opened 2022-10-13 15:15 UTC by DangirasH

2022-10-13 15:18 UTC, SkeidoK submitted a review, later dismissed

2022-10-13 15:23 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-13 15:26 UTC, YDrogen requested changes

2022-10-13 15:26 UTC, YDrogen commented on src/components/movieslisthome/MoviesListHome.jsx
> +import React, { useEffect, useState } from "react";
`import React` ne sert à rien

2022-10-13 15:26 UTC, YDrogen commented on src/components/movieslisthome/MoviesListHome.jsx
> +    const trends = response["results"];
`const { results } = response`
ou
`const trends = response.results`

2022-10-14 07:32 UTC, SkeidoK submitted a review, later dismissed

2022-10-14 07:33 UTC, epereira submitted a review, later dismissed

2022-10-14 07:48 UTC, YDrogen requested changes

2022-10-14 07:48 UTC, YDrogen commented on src/components/movieslisthome/MoviesListHome.jsx
> +            ?.filter((t) => t.media_type === "movie")
Le `.filter` et `.slice` s'execute à chaque render, même si `trending` ne change pas
-> pas opti

2022-10-14 07:48 UTC, YDrogen commented on src/components/movieslisthome/MoviesListHome.jsx
> +            ?.filter((t) => t.media_type === "tv")
idem

2022-10-14 08:28 UTC, epereira approved these changes

2022-10-14 08:51 UTC, epereira approved these changes

2022-10-14 08:57 UTC, YDrogen approved these changes

2022-10-14 08:58 UTC, SkeidoK approved these changes

2022-10-14 08:58 UTC, merged