add movies route
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #21
Opened 2022-10-14 10:10 UTC by epereira

2022-10-14 10:39 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-14 12:00 UTC, DangirasH submitted a review, later dismissed

2022-10-14 12:36 UTC, YDrogen requested changes

2022-10-14 12:36 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +  let { movieId } = useParams();
???

2022-10-14 12:36 UTC, YDrogen commented on src/pages/detail/Movie.jsx
>                      .slice(0, 3)
le `.filter().slice()` se déclenche à chaque rerender
Ce n'est pas opti

2022-10-14 12:57 UTC, epereira commented on src/pages/detail/Movie.jsx
> +  let { movieId } = useParams();
oui monsieur, la recommandation de la doc officielle du router (c'est bien un 'let' et non un 'const')
https://reactrouter.com/en/main/hooks/use-params

2022-10-14 13:00 UTC, epereira commented on src/pages/detail/Movie.jsx
>                      .slice(0, 3)
Ce n'est pas dans la PR Monsieur !
Cela sera revu dans une prochaine PR

2022-10-14 14:01 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +  let { movieId } = useParams();
Alors, justement, dans cette même doc officielle : ![doc](https://i.imgur.com/QrkAbHM.png)
`useParams()` retourne une valeur `Readonly` (Lecture seule), donc aucune raison d'être dans un `let` puisqu'on ne peut pas l'écraser

2022-10-14 14:02 UTC, YDrogen commented on src/pages/detail/Movie.jsx
>                      .slice(0, 3)
![no](https://media.tenor.com/TpnPWXyeCJcAAAAC/non-mario.gif)

2022-10-14 14:17 UTC, epereira commented on src/pages/detail/Movie.jsx
> +  let { movieId } = useParams();
![image](https://user-images.githubusercontent.com/374449/195869189-518e5a9e-a292-4601-88ae-c5cb3e9026df.png)

2022-10-14 14:23 UTC, epereira commented on src/pages/detail/Movie.jsx
>                      .slice(0, 3)
Ca n'a rien à faire dans cette PR, il n'y a que les liens et des routes sur celles-ci et la variable concernée par la route.

2022-10-14 14:37 UTC, YDrogen commented
![no](https://media.tenor.com/q0bZA7Q3LUkAAAAC/you-shall-not-pass-lord-of-the-ring.gif)

2022-10-14 15:12 UTC, paul-chatelain-fernandes approved these changes

2022-10-14 15:12 UTC, SkeidoK approved these changes

2022-10-16 12:52 UTC, epereira commented on src/pages/detail/Movie.jsx
>                      .slice(0, 3)
cette partie est déjà dans develop mais ne concerne pas cette PR, merci de votre compréhension... ;-)
Une PR à part sera prévue pour optimiser ce bout de code.

2022-10-17 09:19 UTC, YDrogen approved these changes

2022-10-19 07:25 UTC, merged