Category movie page
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #22
Opened 2022-10-19 09:48 UTC by SkeidoK

2022-10-19 12:05 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-19 12:35 UTC, DangirasH submitted a review, later dismissed

2022-10-19 12:45 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-19 12:47 UTC, YDrogen approved these changes

2022-10-19 12:47 UTC, YDrogen requested changes

2022-10-19 12:47 UTC, YDrogen commented on src/App.jsx
> +          <Route path="category/:genre" element={<CategoryPage />} />
il manque un /

2022-10-19 15:22 UTC, DangirasH approved these changes

2022-10-20 07:12 UTC, paul-chatelain-fernandes approved these changes

2022-10-20 07:17 UTC, YDrogen approved these changes

2022-10-20 07:17 UTC, merged