S03 movie page improve
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #24
Opened 2022-10-19 14:39 UTC by epereira

2022-10-19 14:43 UTC, DangirasH submitted a review, later dismissed

2022-10-19 14:44 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-19 14:52 UTC, YDrogen requested changes

2022-10-19 14:52 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
Est-ce que le `controller` est utilisé quelque part ?

2022-10-20 13:02 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
oui dans le dismount du useEffect

2022-10-20 13:04 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
À part ça, il est utilisé quelque part ?

2022-10-20 13:07 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
En clair tu veux dire quoi ? que tous les useEffect() doivent avoir le même controller ?

2022-10-20 13:16 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
Le `return` sert à "nettoyer" les process qui pourraient tourner en fond. Le `controller` sert à stopper les requêtes HTTP si le `component` est démonté.
Ici, il n'y a pas de requête d'envoyée, le seul "usage" du `controller` est dans le `return`, donc pas vraiment une utilisation

2022-10-20 14:12 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
Merci pour les explications ;-) je vais retirer le controller et  laisser tourner deux fois le useEffect() alors, au pire je pourrais mettre un boolean pour éviter ça ?

2022-10-20 14:20 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
Pas besoin

Le fait que le `useEffect` tourne 2 fois permet d'anticiper les fuites de mémoire et les bugs qui pourraient survenir lorsqu'il est mal fait. Là, à part le `controller` tout est ok 👌

Dans le `return` on trouve souvent des `AbortController` quand il y a une requête HTTP, des `clearTimeout` ou `clearInterval`, des `.removeEventListener`, etc..

2022-10-20 15:05 UTC, epereira commented on src/pages/detail/Movie.jsx
> +    const controller = new AbortController();
ok

2022-10-20 15:07 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-20 15:22 UTC, DangirasH submitted a review, later dismissed

2022-10-21 07:16 UTC, paul-chatelain-fernandes submitted a review, later dismissed

2022-10-21 07:40 UTC, DangirasH submitted a review, later dismissed

2022-10-21 08:01 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-21 08:10 UTC, YDrogen commented on src/pages/detail/Movie.jsx
> +                    <div key={c.id} className="relative mr-6">
Pourquoi tu mets pas le `hover:scale-125` ici ?

2022-10-21 08:14 UTC, epereira commented on src/pages/detail/Movie.jsx
> +                    <div key={c.id} className="relative mr-6">
T'es un génie ;-)

2022-10-21 08:17 UTC, epereira commented on src/pages/detail/Movie.jsx
> +                    <div key={c.id} className="relative mr-6">
Corrigé

2022-10-21 08:18 UTC, SkeidoK approved these changes

2022-10-21 08:18 UTC, paul-chatelain-fernandes approved these changes

2022-10-21 08:56 UTC, YDrogen approved these changes

2022-10-21 08:56 UTC, merged