add dropdown
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #36
Opened 2022-10-26 13:31 UTC by SkeidoK

2022-10-26 15:02 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-27 08:00 UTC, DangirasH submitted a review, later dismissed

2022-10-27 08:19 UTC, YDrogen requested changes

2022-10-27 08:19 UTC, YDrogen commented on src/pages/typepage/CategoryPage.jsx
> +            navigate(`/category/${type}/${genre}/${parseInt(pageNumber) - 1}`)
non dimenticare la base nel parseI ente

2022-10-28 09:26 UTC, paul-chatelain-fernandes approved these changes

2022-10-28 12:36 UTC, DangirasH approved these changes

2022-10-28 18:08 UTC, YDrogen approved these changes

2022-10-28 19:30 UTC, merged