put searchbar in header
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #40
Opened 2022-10-27 09:32 UTC by DangirasH

2022-10-27 12:28 UTC, epereira approved these changes, later dismissed

2022-10-27 14:44 UTC, paul-chatelain-fernandes approved these changes, later dismissed

2022-10-27 15:08 UTC, epereira submitted a review, later dismissed

2022-10-27 15:12 UTC, YDrogen requested changes

2022-10-27 15:12 UTC, YDrogen commented on src/pages/home/Home.jsx
> +        {" "}
Pourquoi ??

2022-10-27 15:26 UTC, paul-chatelain-fernandes approved these changes

2022-10-27 15:30 UTC, epereira approved these changes

2022-10-28 18:03 UTC, YDrogen approved these changes

2022-10-31 08:38 UTC, merged