S05 us11 person responsive
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #57
Opened 2022-11-02 15:46 UTC by paul-chatelain-fernandes

2022-11-02 15:48 UTC, SkeidoK approved these changes, later dismissed

2022-11-02 15:56 UTC, epereira submitted a review, later dismissed

2022-11-02 16:09 UTC, YDrogen requested changes

2022-11-02 16:09 UTC, YDrogen commented on src/pages/detail/Person.jsx
> +        if (personDetails.deathday != null) {
triple =

2022-11-02 16:09 UTC, YDrogen commented on src/pages/detail/Person.jsx
> +                {age != null ? age : null} years
idem

2022-11-02 16:20 UTC, YDrogen approved these changes

2022-11-02 16:30 UTC, epereira approved these changes

2022-11-03 08:06 UTC, SkeidoK approved these changes

2022-11-03 08:06 UTC, merged