Guide return
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #71
Opened 2022-11-03 15:46 UTC by DangirasH

2022-11-03 15:47 UTC, SkeidoK approved these changes

2022-11-03 15:57 UTC, paul-chatelain-fernandes requested changes

2022-11-03 15:57 UTC, paul-chatelain-fernandes commented on src/components/guide/Guide.jsx
> +            <img src="public/images/return.png"></img>
Just one tag < img />, and miss alt attribute inside img tag

2022-11-03 15:57 UTC, paul-chatelain-fernandes commented on src/components/guide/Guide.jsx
> +              <img src="public/images/return.png"></img>
Idem as above

2022-11-03 15:57 UTC, SkeidoK submitted a review, later dismissed

2022-11-04 07:36 UTC, SkeidoK approved these changes

2022-11-04 07:50 UTC, paul-chatelain-fernandes approved these changes

2022-11-04 08:05 UTC, YDrogen approved these changes

2022-11-04 08:05 UTC, YDrogen commented on src/components/guide/Guide.jsx
> +        <div className="movieList">
Les classnames doivent avoir des -

2022-11-04 08:10 UTC, merged