Added all searchbar features
WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK pull request #8
Opened 2022-10-05 15:12 UTC by paul-chatelain-fernandes

2022-10-05 15:23 UTC, DangirasH approved these changes

2022-10-05 15:24 UTC, DangirasH requested changes
Do not remove tailwind.config

2022-10-05 15:29 UTC, DangirasH submitted a review, later dismissed

2022-10-06 14:48 UTC, SkeidoK submitted a review, later dismissed

2022-10-06 14:53 UTC, DangirasH approved these changes, later dismissed

2022-10-06 15:00 UTC, YDrogen commented on src/components/searchbar/Searchbar.jsx
> +  let isMovie = true;
????????????????????????

2022-10-06 15:10 UTC, YDrogen commented on src/components/searchbar/Searchbar.jsx
> +  let isMovie = true;
```javascript
const [isMovie, setMovie] = useState(true);

// useEffect ici avec ton if
```
ou
```javascript
const isMovie = cat !== 'tv'
```

2022-10-07 07:19 UTC, SkeidoK submitted a review, later dismissed

2022-10-07 07:20 UTC, DangirasH approved these changes, later dismissed

2022-10-07 07:25 UTC, epereira submitted a review, later dismissed

2022-10-07 07:25 UTC, YDrogen requested changes

2022-10-07 07:25 UTC, YDrogen commented on src/components/searchbar/Searchbar.jsx
> +    const debounce = setTimeout(() => {
Ce n'est pas un debounce
Ce code va juste rajouter à délai de 500ms quand on écrit

2022-10-07 07:27 UTC, paul-chatelain-fernandes commented on src/components/searchbar/Searchbar.jsx
> +    const debounce = setTimeout(() => {
Oui c'est pour éviter de faire trop d'appels API

2022-10-07 07:46 UTC, SkeidoK approved these changes

2022-10-07 08:04 UTC, DangirasH approved these changes

2022-10-07 08:20 UTC, YDrogen approved these changes

2022-10-07 08:21 UTC, merged